# -*- coding: utf-8 -*-
"""Data Gathering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R03oICp207l2HNnEKsiGUSl0aN3-J8cQ

#1 Import required datasets
"""

#Install yahoo finance to get the stock data
!pip install yfinance

#Import necessary libraries
import yfinance as yf
import pandas as pd

"""#2 Get all stock data"""

# Set the start and end date
start_date = '2012-01-12'
end_date = '2021-08-16'

# Set the ticker
# AAPL = Apple Stock 
# BA = Boeing 
# T = AT&T
# MGM = MGM Resorts International (Hotel Industry)
# AMZN = Amazon
# IBM = IBM
# TSLA = Tesla Motors
# GOOG = Google 
# sp500
ticker = ['AAPL','BA','T','MGM','AMZN','IBM','TSLA','GOOG','^GSPC']

# Get the data
data = yf.download(ticker, start_date, end_date)

#Checking the data
data

#Checking the type of the return result of yahoo finance
type(data)

"""#3 Extracting the Stock Closing price data"""

#Getting only the Closing Prices of the stocks and storing them in a dataframe
#Since there is chained indexing for columns in the dataset, it is better to get a copy
#Because the loc or normal retrievl (using []) won't guarantee a copy or view and hence might raise a 'SettingWithCopy' warning
stock_df = data.loc[:,'Close'].copy()
stock_df.head()

stock_df.rename(columns={'^GSPC':'sp500'},inplace=True)

stock_df.reset_index(inplace=True)

"""#4 Extracting the Stock Volume data"""

stock_volume_df = data.loc[:,'Volume'].copy()
stock_volume_df.head()

stock_volume_df.rename(columns={'^GSPC':'sp500'},inplace=True)

stock_volume_df.reset_index(inplace=True)

stock_volume_df

"""#5 Saving the data on drive in csv format"""

from google.colab import drive
drive.mount('/content/drive')

stock_df.to_csv('/content/drive/MyDrive/Colab Notebooks/Udemy Python/Data/stock.csv')

stock_volume_df.to_csv('/content/drive/MyDrive/Colab Notebooks/Udemy Python/Data/stock_volume.csv')

